# action.yml
name: 'parse-review-comments'
description: 'Gets the review from PR and parse it '
inputs:
  GITHUB_TOKEN:
    description: "A GitHub token for the repo"
    required: false
    default: ${{ github.token }}
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --token
    - ${{ inputs.GITHUB_TOKEN }}
